### ISSUE TITLE
Mephisto no attribute histogram2d

### ISSUE THREAD

**Issue by AomineKKL** [tud-zih-energy/pymit#3]
Hi i faced this problem when running the code from (https://github.com/ranyus/FedFS) and code from here.  This is the error and is there anyway to solve this? 

D:\Anaconda\python.exe F:\FedFS\src\main_fedfs.py 
10 workers holding 45 patterns, respectively
Running Federated Crossentropy with alpha 1.0
*** New Configuration: [nodes 1.0, data 1.0]
bitmap size: 1 byte
Using 10 workers. Max rounds 300
Round 0
FS distribution: [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
Traceback (most recent call last):
  File "F:\FedFS\src\main_fedfs.py", line 102, in <module>
    main()
  File "F:\FedFS\src\main_fedfs.py", line 83, in main
    fs, net, prob, conv_round, fed_running_fs, fed_running_prob, dwl_data_before_conv, max_rounds, alpha_per_round = ffs.federated_feature_selection(X_train, y_train, idxs,fraction_selected_workers=frac_nodes,fraction_local_subsample=frac_data,early_stop_tolerance=tolerance, ce_selection_prob=selection_prob,ce_tolerance=ce_tol, alpha=alpha_smooth, alpha_step=alpha_step,max_sample_ce=ce_max_samples, max_step_ce=ce_max_steps, fed_max_round=MAX_ROUND,verbose=True, verbose_scenario=False,njobs=njobs)
  File "F:\FedFS\src\federated_feature_selection.py", line 98, in federated_feature_selection
    _, fsdist, _, _, ce_steps, cur_alpha = ce.get_features_ce(X_loc, y_loc, 
  File "F:\FedFS\src\crossentropy.py", line 64, in get_features_ce
    obj_fun[i, :] = [i, mit.H_cond(YY, outvec, bins=[classes, maxVal])]
  File "F:\pymit\pymit\entropy.py", line 52, in H_cond
    p_xy, _, _ = pymit._lib.histogram2d(X, Y, bins=[xbins, ybins])
AttributeError: module 'mephisto' has no attribute 'histogram2d'

Process finished with exit code 1

**Comment by AndreasGocht** [comment]
Hey,

the code is written to work on Linux, not necessarily on Windows. Not sure this is the issue through. I'll have a look at this as soon as I find some time.

In the meantime, you might want to try WSL, which provides Linux on Windows.

Best

Andreas

**Comment by AndreasGocht** [comment]
Thinking a bit more about it: How did you setup the python environment, an how did you install pymit?
